name: GitHub Actions Test
on: 
  - push:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        npm run build
        echo "hello"
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
        npm run lint
        echo "hello"