name: GitHub Actions Test
on: 
  push:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - run: npm run lint